---
# yamllint disable rule:line-length
###############################################################################
# Automatically reboot system after period of time.
###############################################################################
#
# Reference:
# * https://gist.github.com/hkoba/e05c91ebdd4e2ffd1d79e78e76cf1ff5
# * https://opensource.com/article/20/7/systemd-timers

- name: 'Optimizations | auto reboot | create reboot timer service'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.systemd'
  vars:
    systemd_services:
      - name: 'reboot'
        unit:
          description: 'periodic system reboot service'
          requires: ['reboot.timer']
        service:
          type: 'simple'
          exec_start: ['/usr/bin/systemctl --force reboot --when={{ debian_optimizations_reboot_variance | ansible.builtin.random(start=0, seed=inventory_hostname) }}s']
        exec:
          user: 'root'
        state: 'present'
    systemd_timers:
      - name: 'reboot'
        unit:
          description: 'periodic system reboot timer'
        timer:
          unit: 'reboot.service'
          on_boot_sec: '{{ debian_optimizations_reboot | default("1month") }}'
        install:
          wanted_by: ['timers.target']
        state: 'present'
  when: debian_optimizations_reboot | length > 0

- name: 'Optimizations | auto reboot | disable reboot timer service'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.systemd'
  vars:
    systemd_services:
      - name: 'reboot'
        state: 'absent'
    systemd_timers:
      - name: 'reboot'
        state: 'absent'
  when: debian_optimizations_reboot | length == 0
