---
###############################################################################
# Manage MOTD messaging
###############################################################################

- name: 'Optimizations | MOTD | set MOTD'
  ansible.builtin.copy:
    dest: '/etc/motd'
    content: '{{ debian_optimizations_motd }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true
