---
# yamllint disable rule:line-length
###############################################################################
# Display extended uptime reboot notification.
###############################################################################

- name: 'Optimizations | reboot notifications | add extended uptime reboot notification'
  ansible.builtin.template:
    src: '98-reboot-required.j2'
    dest: '/etc/update-motd.d/98-reboot-required'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: debian_optimizations_motd_extended_reboot

- name: 'Optimizations | reboot notifications | clear extended uptime reboot notification'
  ansible.builtin.file:
    path: '/etc/update-motd.d/98-reboot-required'
    state: 'absent'
  when: not debian_optimizations_motd_extended_reboot
