---
- name: 'Skeleton files | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Skeleton files | converge | run skeleton_files.yml'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.debian'
        tasks_from: 'skeleton_files.yml'
