---
# yamllint disable rule:line-length
- name: 'Skeleton files | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Skeleton files | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'rsync'  # ansible.builtin.synchronize (rsync)
        update_cache: true
        state: 'present'
