---
# yamllint disable rule:line-length
- name: 'Skeleton files | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Skeleton files | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'python3-debian'  # deb-822 apt source support.
          - 'locales'  # locales support.
        update_cache: true
        state: 'present'
