---
# yamllint disable rule:line-length
# Assert .bash_logout source file is written.
- name: 'Skeleton files | verify | .bash_logout'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Skeleton files | verify | optimizations | query /etc/skel/.bash_logout'
      ansible.builtin.slurp:
        path: '/etc/skel/.bash_logout'
      register: _test_debian_skeleton_files

    - name: 'Skeleton files | verify | optimizations | assert .bash_logout'
      ansible.builtin.assert:
        that:
          - _test_debian_skeleton_files.content | b64decode == "echo 'test skel .bash_logout'"
        fail_msg: "/etc/skel/.bash_profile invalid (expected echo 'test skel .bash_logout')."

    - name: 'Skeleton files | verify | skeleton | query default skel files'
      ansible.builtin.find:
        paths: '/etc/skel'
        recurse: false
        hidden: true
        file_type: 'file'
      register: _test_debian_skel

    - name: 'Skeleton files | verify | skeleton | assert default skel files'
      ansible.builtin.assert:
        that:
          - _test_debian_skel.files | length == 1
        fail_msg: '/etc/skel/.bash_logout not found.'
