---
# Assert only .bash_logout source file is written to skeleton directory.
- name: 'Skeleton files | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Skeleton files | verify | query expected .bash_logout'
      ansible.builtin.copy:
        src: 'files/.bash_logout'
        dest: '/etc/skel/.bash_logout'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_debian_skeleton_files

    - name: 'Skeleton files | verify | assert expected .bash_logout'
      ansible.builtin.assert:
        that:
          - not _test_debian_skeleton_files.changed
        fail_msg: >
          /etc/skel/.bash_logout is not in expected format:
          {{ _test_debian_skeleton_files.diff }}.

    - name: 'Skeleton files | verify | query number of files'
      ansible.builtin.find:
        paths: '/etc/skel'
        recurse: false
        hidden: true
        file_type: 'file'
      register: _test_debian_skeleton_files_count

    - name: 'Skeleton files | verify | assert expected number of files'
      ansible.builtin.assert:
        that:
          - _test_debian_skeleton_files_count.files | length == 1
        fail_msg: '/etc/skel/.bash_logout not found.'
