---
- name: 'Install packages'
  when: debian_role_packages | length > 0
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages: '{{ debian_role_packages }}'
    apt_package_update_cache: true

- name: 'Locales'
  ansible.builtin.import_tasks: 'locales.yml'
- name: 'Timezone'
  ansible.builtin.import_tasks: 'timezone.yml'

- name: 'MOTD'
  ansible.builtin.import_tasks: 'motd.yml'

- name: 'Inotify limit'
  when: debian_inotify_limit >= 0
  ansible.builtin.import_tasks: 'inotify_limit.yml'

- name: 'Skeleton files'
  when: debian_skeleton_files | length > 0
  ansible.builtin.import_tasks: 'skeleton_files.yml'

- name: 'Auto reboot'
  ansible.builtin.import_tasks: 'auto_reboot.yml'

- name: 'Lockdown home'
  when: debian_lockdown_home
  ansible.builtin.import_tasks: 'lockdown_home.yml'

- name: '/tmp'
  when: debian_tmp_ram
  ansible.builtin.import_tasks: 'tmp.yml'

# Force cron restart for timezone changes
- name: 'Flush handlers'
  ansible.builtin.meta: 'flush_handlers'
