---
- name: 'Apt | sources'
  ansible.builtin.import_tasks: 'apt/sources.yml'
- name: 'Apt | packages'
  ansible.builtin.import_tasks: 'apt/packages.yml'
- name: 'Apt | unattended'
  ansible.builtin.import_tasks: 'apt/unattended.yml'

- name: 'SSH'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.ssh'

- name: 'Locales'
  ansible.builtin.import_tasks: 'locales.yml'
- name: 'Timezone'
  ansible.builtin.import_tasks: 'timezone.yml'
- name: 'Optimizations | TCP BBR'
  ansible.builtin.import_tasks: 'optimizations/tcp_bbr.yml'
  when: debian_optimizations_tcp_bbr_enable

- name: 'Network | IPv6'
  ansible.builtin.import_tasks: 'network/ip_v6.yml'

- name: 'UFW'
  ansible.builtin.import_role:
    name: 'r_pufky.srv.ufw'

- name: 'Optimizations | MOTD'
  ansible.builtin.import_tasks: 'optimizations/motd.yml'

- name: 'Logrotate'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.logrotate'

- name: 'Journald'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.journald'

- name: 'Optimizations | inotify limit'
  ansible.builtin.import_tasks: 'optimizations/inotify_limit.yml'
  when: debian_optimizations_inotify_limit >= 0

- name: 'Skeleton files'
  ansible.builtin.import_tasks: 'skeleton_files.yml'
  when: debian_skeleton_files | length > 0

- name: 'Optimizations | reboot notifications'
  ansible.builtin.import_tasks: 'optimizations/reboot_notifications.yml'
- name: 'Optimizations | auto reboot'
  ansible.builtin.import_tasks: 'optimizations/auto_reboot.yml'

- name: 'Accounts'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.users'
    tasks_from: 'user.yml'
  loop: '{{ debian_accounts | default([]) }}'
  loop_control:
    loop_var: user

- name: 'Optimizations | lockdown home'
  ansible.builtin.import_tasks: 'optimizations/lockdown_home.yml'
  when: debian_optimizations_lockdown_home

- name: 'GPU passthrough'
  ansible.builtin.import_tasks: 'gpu_passthrough/main.yml'
  when: debian_gpu_passthrough

- name: 'Network | interfaces'
  ansible.builtin.import_tasks: 'network/interfaces.yml'

# TODO(role): Keep this until all dependent roles are migrated to systemd, then
#     deprecate these tasks (heavily favor systemd) but keep to provide cron
#     setup for any additional services.
#
# Reference:
# * https://wiki.debian.org/cron
- name: 'Cron'
  ansible.builtin.include_tasks: 'cron.yml'
  vars:
    job_name: '{{ item.key }}'
    config: '{{ item.value }}'
  loop: '{{ debian_cron | default({}) | dict2items }}'

- name: 'Flush handlers'
  ansible.builtin.meta: 'flush_handlers'
