---
###############################################################################
# Manage MOTD messaging
###############################################################################

- name: 'MOTD | set'
  ansible.builtin.copy:
    dest: '/etc/motd'
    content: '{{ debian_motd }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true

- name: 'MOTD | add extended uptime reboot notification'
  when: debian_motd_extended_reboot_warning
  ansible.builtin.template:
    src: '98-reboot-required.j2'
    dest: '/etc/update-motd.d/98-reboot-required'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'MOTD | clear extended uptime reboot notification'
  when: not debian_motd_extended_reboot_warning
  ansible.builtin.file:
    path: '/etc/update-motd.d/98-reboot-required'
    state: 'absent'
