---
# Idempotent testing disabled as specific commands will never be idempotent.
#
# Reference:
# * https://github.com/ansible/molecule/issues/816

- name: 'Cron | converge'
  hosts: all
  gather_facts: true
  tags: 'molecule-idempotence-notest'
  tasks:
    - name: 'Cron | converge | apply debian role add cronjobs'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.debian'

    - name: 'Cron | converge | apply debian role remove cronjob '
      ansible.builtin.include_role:
        name: 'r_pufky.srv.debian'
      vars:
        debian_cron:
          cron_absent:
            state: 'absent'
