---
- name: 'Cron | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Cron | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'cron'  # ansible.builtin.cron (cron)
        update_cache: true
        state: 'present'
