---
# yamllint disable rule:line-length
# Encapsulated roles are just verified to execute without error (tested in that
# role). Only test new tasks within this role.
# - name: 'Cron | verify | skeleton files'
#   hosts: 'all'
#   gather_facts: false
#   tasks:
#     - name: 'Cron | verify | skeleton files | query default skel files'
#       ansible.builtin.find:
#         paths: '/etc/skel'
#         recurse: false
#         hidden: true
#         file_type: 'file'
#       register: _test_debian_skel
#
#     - name: 'Cron | verify | skeleton files | assert default skel files'
#       ansible.builtin.assert:
#         that:
#           - _test_debian_skel.files | length == 3
#         fail_msg: '/etc/skel/{.bash_logout,.bashrc,.profile} not found.'

- name: 'Cron | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Cron | verify | query system cron jobs'
      ansible.builtin.find:
        paths: '/etc/cron.d'
        file_type: 'file'
      changed_when: false
      register: _test_debian_cron_list

    - name: 'Cron | verify | assert cron job created'
      ansible.builtin.lineinfile:
        path: '/etc/cron.d/debian_custom_cron_cron_present'
        regex: '.*cron_present.*'
        state: 'absent'
      changed_when: false
      check_mode: true
      register: _test_debian_cron
      failed_when: _test_debian_cron.found == 0

    - name: 'Cron | verify | assert cron job deleted'
      ansible.builtin.lineinfile:
        path: '/etc/cron.d/debian_custom_cron_cron_absent'
        regex: '.*cron_absent.*'
        state: 'absent'
      changed_when: false
      check_mode: true
      register: _test_debian_cron
      failed_when: '"found" in _test_debian_cron'

    - name: 'Cron | verify | cron | assert only debian_custom_cron_cron_present'
      ansible.builtin.assert:
        that:
          - _test_debian_cron_list.files | length == 2
        fail_msg: '/etc/cron.d should contain only e2scrub_all, debian_custom_cron_cron_present.'
