---
###############################################################################
# Debian Handlers
###############################################################################

- name: 'Handlers | restart unattended-upgrades'
  ansible.builtin.service:
    name: 'unattended-upgrades'
    state: 'restarted'
    enabled: true

- name: 'Handlers | reload systemd'
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: 'Handlers | restart cron'
  ansible.builtin.service:
    name: 'cron'
    state: 'restarted'

- name: 'Handlers | ifreload'
  ansible.builtin.command: '/sbin/ifreload -a'
  become: true
  changed_when: false

- name: 'Handlers | restart networking'
  when: debian_optimizations_systemctl_network_restart
  ansible.builtin.service:
    name: 'networking'
    state: 'restarted'
  changed_when: true
