---
###############################################################################
# Configure Debian Cron
###############################################################################
# Create custom cronjobs to execute on the Debian node.
#
# Modern job scheduling is highly preferred to cronjobs for security, resource
# management, time resolution, event-based triggering, centralized logging, and
# dependency management.
#
# Args:
#   job_name: str - cron job name (debian_cron.{JOB})
#   config: dict - cron job configuration (debian_cron.{JOB}.*)
#
# Reference:
# * https://wiki.debian.org/cron
# * https://unix.stackexchange.com/questions/278564/cron-vs-systemd-timers
# * https://gist.github.com/hkoba/e05c91ebdd4e2ffd1d79e78e76cf1ff5
# * https://wiki.archlinux.org/title/Systemd/Timers#As_a_cron_replacement
# * https://opensource.com/article/20/7/systemd-timers

- name: 'Cron | DEPRECATED | actively migrate to systemd timer services'
  ansible.builtin.debug:
    msg: |
      Cronjobs should actively be migrated to modern job scheduling if able.

      Use systemd timers.

      See:
      * debian_systemd_services
      * debian_systemd_timers
      * r_pufky.srv.systemd

      https://opensource.com/article/20/7/systemd-timers
      https://wiki.archlinux.org/title/Systemd/Timers#As_a_cron_replacement
  when: not debian_cron_warning_disable

- name: 'Cron | set standard scheduling sync'
  ansible.builtin.cron:
    name: 'debian custom cron {{ job_name }}'
    month: '{{ config.month | default("*") }}'
    weekday: '{{ config.weekday | default("*") }}'
    day: '{{ config.day | default("*") }}'
    hour: '{{ config.hour | default("*") }}'
    minute: '{{ config.minute | default("*") }}'
    user: '{{ config.user | default("root") }}'
    job: '{{ config.job | default(omit) }}'
    cron_file: 'debian_custom_cron_{{ job_name }}'
    state: '{{ config.state | default("present") }}'
  when: config.special_time is not defined

- name: 'Cron | set special time sync'
  ansible.builtin.cron:
    name: 'debian custom cron {{ job_name }}'
    special_time: '{{ config.special_time }}'
    user: '{{ config.user | default("root") }}'
    job: '{{ config.job | default(omit) }}'
    cron_file: 'debian_custom_cron_{{ job_name }}'
    state: '{{ config.state | default("present") }}'
  when: config.special_time is defined
