---
###############################################################################
# Default Debian Package Dependencies
###############################################################################

# Last time debian options were validated against a default configuration.
debian_role_validate_date: '2024-06-25'
debian_role_validate_release: 'bookworm'

# Default state for apt package installation. See ansible.builtin.apt.
debian_role_package_state: 'latest'

# Default debian packages required for operation.
debian_role_packages:
  - 'rsync'  # ansible.posix.synchronize.

# Default packages for unattended upgrades.
debian_role_unattended_upgrades_packages:
  - 'apt-listchanges'  # installed by default.
  - 'unattended-upgrades'  # installed by default.
  - 'apt-config-auto-update'  # config automation support.

# Default packages to enable unattended upgrades on AC power.
debian_role_ac_power_packages:
  - 'powermgmt-base'
