---
- name: 'Default | verify | skeleton files'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | skeleton files | query default skel files'
      ansible.builtin.find:
        paths: '/etc/skel'
        recurse: false
        hidden: true
        file_type: 'file'
      register: _test_debian_skel

    - name: 'Default | verify | skeleton files | assert default skel files'
      ansible.builtin.assert:
        that:
          - _test_debian_skel.files | length == 3
        fail_msg: '/etc/skel/{.bash_logout,.bashrc,.profile} not found.'

- name: 'Default | verify | network'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | network | query /etc/network/interfaces'
      ansible.builtin.stat:
        path: '/etc/network/interfaces'
      register: _test_debian_network_interfaces

    - name: 'Default | verify | network | assert interfaces not configured'
      ansible.builtin.assert:
        that:
          - not _test_debian_network_interfaces.stat.exists
        fail_msg: '/etc/network/interfaces should not exist (not configured).'

- name: 'Default | verify | cron'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | cron | query system cron jobs'
      ansible.builtin.find:
        paths: '/etc/cron.d'
        file_type: 'file'
      changed_when: false
      register: _test_debian_cron

    - name: 'Default | verify | cron | assert no cron jobs'
      ansible.builtin.assert:
        that:
          - _test_debian_cron.files | length == 1  # default only e2scrub_all
        fail_msg: >
          /etc/cron.d has additional cron jobs (only e2scrub_all should exist).
