---
# yamllint disable rule:line-length
###############################################################################
# Apt Source List
###############################################################################
# Reference:
# * https://wiki.debian.org/SourcesList

- name: 'Apt | sources | modify apt sources'
  ansible.builtin.deb822_repository:
    allow_downgrade_to_insecure: '{{ item.allow_downgrade_to_insecure | default(omit) }}'
    allow_insecure: '{{ item.allow_insecure | default(omit) }}'
    allow_weak: '{{ item.allow_weak | default(omit) }}'
    architectures: '{{ item.architectures | default(omit) }}'
    by_hash: '{{ item.by_hash | default(omit) }}'
    check_valid_until: '{{ item.check_valid_until | default(omit) }}'
    components: '{{ item.components | default(omit) }}'
    date_max_future: '{{ item.date_max_future | default(omit) }}'
    enabled: '{{ item.enabled | default(omit) }}'
    inrelease_path: '{{ item.inrelease_path | default(omit) }}'
    languages: '{{ item.languages | default(omit) }}'
    mode: '{{ item.mode | default("0644") }}'
    name: '{{ item.name }}'
    pdiffs: '{{ item.pdiffs | default(omit) }}'
    signed_by: '{{ item.signed_by }}'
    state: '{{ item.state | default("present") }}'
    suites: '{{ item.suites | default(omit) }}'
    targets: '{{ item.targets | default(omit) }}'
    trusted: '{{ item.trusted | default(omit) }}'
    types: '{{ item.types | default(["deb"]) }}'
    uris: '{{ item.uris }}'
  loop: '{{ debian_apt_sources }}'

- name: 'Apt | sources | update cache'
  ansible.builtin.apt:
    update_cache: true

- name: 'Apt | sources | upgrade packages (may take a while)'
  ansible.builtin.debug:
    msg: |
      Packages are being upgraded. This will take a few minutes.
  when: debian_apt_dist_upgrade_enable

- name: 'Apt | sources | upgrade distribution packages'
  ansible.builtin.apt:
    upgrade: 'dist'
    state: '{{ debian_role_package_state }}'
    update_cache: true
  async: 600
  poll: 5
  when: debian_apt_dist_upgrade_enable
