---
###############################################################################
# Unattended Updates and Upgrades.
###############################################################################
# Setup automatic updates and reboots.
#
# Reference:
# * https://wiki.debian.org/UnattendedUpgrades
# * /etc/cron.daily/apt-compat
# * /usr/lib/apt/apt.systemd.daily

- name: 'Apt | unattended | install packages'
  ansible.builtin.apt:
    name: '{{ debian_role_unattended_upgrades_packages }}'
    state: '{{ debian_role_package_state }}'

- name: 'Apt | unattended | install AC power management detection'
  ansible.builtin.apt:
    name: '{{ debian_role_ac_power_packages }}'
    state: '{{ debian_role_package_state }}'
  when: debian_unattended_ac_only_enable

- name: 'Apt | unattended | configure auto upgrades'
  ansible.builtin.template:
    src: 'unattended/20auto-upgrades.j2'
    dest: '/etc/apt/apt.conf.d/20auto-upgrades'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Handlers | restart unattended-upgrades'

- name: 'Apt | unattended | configure unattended-upgrades'
  ansible.builtin.template:
    src: 'unattended/50unattended-upgrades.j2'
    dest: '/etc/apt/apt.conf.d/50unattended-upgrades'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Handlers | restart unattended-upgrades'
